### PR TITLE
OXT-369 Aggregate battery stats in UIVM

### PR DESCRIPTION
**Pull request by marslandd**
This updates the UI to read and report aggregate battery statistics
for Charge, Time To Full, and Time to Empty

Signed off by: David Marsland

### CODE REVIEW

**Comment by jean-edouard** [comment]
Builds fine, doesn't seem to break anything. As usual I don't understand the code.
Will merge soon.

**Comment by marslandd** [comment]
I can get Doc to review if you'd like.

**Comment by jean-edouard** [comment]
That's probably a good idea yeah, thanks

**Comment by rossphilipson** [comment]
I agree, please do that, thanks.

**Comment by pentadoc** [comment]
+1

**Comment by jean-edouard** [comment]
Thanks @pentadoc, merging soon

**Pull request merged**
