### PR TITLE
Standardize code to UNIX-style line endings

### PR DESCRIPTION
**Pull request by bennettj1087**
OXT-121

Signed-off-by: Justin Bennett bennettj@ainfosec.com

### CODE REVIEW

**Comment by bennettj1087** [comment]
In an effort to ease everyone's mind, here are the steps used to generate this patch:

```
cd /path/to/toolstack-data.git
find . -type f -not -path "./.git/*" | cut -d. -f3 | sort | uniq
```

This gives you a list of file extensions in the repo, most of them are js, css, html, png and gif, but there are some shell scripts, batch scripts and text files.  We want to convert line endings for js, css, html, txt and sh files.

```
find . -type f -not -path "./.git/*" \( -name "*.js" -o -name "*.css" -o -name "*.html" -o -name "*.js" -o -name "*.json" -o -name "*.sh" -o -name "*.txt" \) -exec file {} \; | grep CRLF | wc -l
```

This shows how many files in the repo are currently set to CRLF that we want to change.  This number is 90.

```
find . -type f -not -path "./.git/*" \( -name "*.js" -o -name "*.css" -o -name "*.html" -o -name "*.js" -o -name "*.json" -o -name "*.sh" -o -name "*.txt" \) -exec dos2unix {} \;
```

This uses `dos2unix` to convert line-endings for all of the files we identified.

**Comment by thegecko** [comment]
Thanks Justin,

Some of the line endings in the Japanese and Chinese language files look suspect in the character-level diff tool I'm using, possibly due to the double-byte character encoding used.
Have you guys checked the system still works correctly in these languages after the change?

It may be a good idea to omit these folders from this PR:

/widgets/xenclient/nls/ja-jp/
/widgets/xenclient/nls/zh-cn/

**Comment by bennettj1087** [comment]
To be honest, I didn't realize the alternate languages were even a thing
that worked. There must be somewhere in the UI to change the language?

I'm all for leaving those directories out of this PR.  I don't foresee
anyone currently on the project working on those languages so for now that
seems like a fine idea.

I will update the PR when I get a chance, possible later today or tomorrow.

**Comment by thegecko** [comment]
Just run your line-ending script and checkout those 2 directories :)

**Comment by bennettj1087** [comment]
I went ahead and pushed a new commit with those two directories left out. I think that seems like a fine idea.

**Comment by thegecko** [comment]
LGTM, ship it!

By the way, the language selection control is hidden at the moment, but I think you can trivially change it by adding ?locale=de-de (or whatever) when opening the UI

**Comment by rossphilipson** [comment]
Was waiting for Rob's ACK, so I am going to merge this now...

**Pull request merged**
