### PR TITLE
Oxt 190  - VM Volume control naming

### PR DESCRIPTION
**Pull request by pentadoc**
Replace domid VM names in audio settings with VM given names and slot shortcuts

Add domid property to vmModel

Add getVMByDomId function to hostModel

OXT-190

Signed-of-by: Andrew "Doc" Docherty doc@coveycs.com

### CODE REVIEW

**Comment by thegecko** [comment]
Ref: https://openxt.atlassian.net/browse/OXT-190

**Comment by thegecko** [comment]
This PR requires merge conflicts to be resolved.

Can we update xenmgr so we don't need the regex to parse vm-domid?
Alternatively, you could add "vm-" to the domid of the VM once loaded.

VM switcher slots can be changed by the user, so the settings screen would need a refresh when this happens.

I am unable to test the changes on hardware, but I would recommend testing:

Starting and stopping VMs and re-checking this list (domids are not reliable and dynamically change based on platform state and what is running at the time)

Changing the assigned switcher slots of VMs and checking this list.

**Comment by thegecko** [comment]
Thinking further on this, I'm not sure having the switcher number in the title adds anything to the UI and it would look better if removed.

**Comment by pentadoc** [comment]
The regex is to determine if the control being processed is either a VM or another audio control; they're all stored the same way in XUICache.Host.audioControls.  I can replace the regex with indexOf to speed up the the string compare if you're really worried about speed.

**Comment by pentadoc** [comment]
I added some code to refresh the XUICache.VMs object whenever a VM starts or stops.  From what I can tell the XUICache.VMs[<path>].domid(s) are now correctly reflecting the domid values in xec-vm.

**Comment by bennettj1087** [comment]
@thegecko Anymore feedback on this one or does it look good to you?

**Comment by thegecko** [comment]
With the slot numbers removed, You no longer need the extra refreshes (which will add a lot of churn to the UI). Can you revert the last commit and re-test?

**Comment by thegecko** [comment]
Also, would you mind adding a screenshot of the fix to the jira ticket?

**Comment by pentadoc** [comment]
After some testing it looks like the refresh still needs to be called, but only when a VM starts. Otherwise, the Audio controls show the "vm-domid" name until the browser is refreshed.

**Comment by thegecko** [comment]
Hmm, that sounds like a refresh is needed when the UI for each VM has finished loading, but I guess the same problem would also appear when renaming a VM

**Comment by pentadoc** [comment]
Renaming a VM from the GUI and/or command line seems to be properly reflected in the Audio controls

**Comment by pentadoc** [comment]
@thegecko Anything else on this ticket?

**Comment by thegecko** [comment]
Nope, all good

**Pull request merged**
