### PR TITLE
Remove parseInt call to avoid incorrect PCI address comparison

### PR DESCRIPTION
**Pull request by pentadoc**
Signed-off-by: Andrew 'Doc' Docherty doc@coveycs.com

### CODE REVIEW

**Comment by jean-edouard** [comment]
Do you have an example of what this fixes?

**Comment by gamorg02** [comment]
I worked with Doc to take a look at this as we were seeing odd behavior with a GPU with a busID of 08 which the parseInt took as base8 due to the leading 0, and being an invalid base8 number, made it 0.  That 0 then matched all other PCI devices (&functions) in the workstation.  We tested this and it fixed the issue on the offending workstation.

**Comment by pentadoc** [comment]
parseInt("08") would return 0 instead of 8

**Comment by jean-edouard** [comment]
Yup, makes sense, +1, will merge soon.

**Pull request merged**
