### PR TITLE
Mitigated memory leak in menu items

### PR DESCRIPTION
**Pull request by weakmint**
Memory leak was present in three locations:
1. _startupwidgets object in Settings dialog needed to be nulled after
   startup
2. Settings widget was adding ~100 event handles every time the
   host model was refreshed. Solution is to remove those handles
   and then add the new handles at refresh.
3. The _connectHandles array in the repeater widget kept adding new
   handles every time the host model refreshed, so now the handles
   are removed prior to adding the new ones

OXT-225

Signed-off-by: Ian Miller ian@coveycs.com

### CODE REVIEW

**Comment by crogers1** [comment]
That whitespace at end of line can be fixed by truncating the file by 1 byte before you make your commit, as the character won't show up explicitly in your editor.

For 2) on your list, is it necessary for the settings widget to add new event handles on refresh?  Is it clear why they weren't being reused in the first place?

**Comment by weakmint** [comment]
The new handles are added because it's possible the audio devices have changed and the Settings dialog needs to update them to reflect any changes. Settings first deletes all the audio controls, then adds them again with any changes if necessary, and then adds new handlers for the controls. 

As far as I can tell, they aren't being reused because there isn't a simple way to tell which handle relates to which control. It's easier to just delete them along with the audio controls, and then re-create everything.

**Comment by bennettj1087** [comment]
+1 

I'm running a build with this fix in it and the memory leak issue is substantially better than it ever was. Is there anything preventing this from being merged?

**Comment by rossphilipson** [comment]
Everybody likes the new newlines so they go in, merging...

**Pull request merged**
