### PR TITLE
OXT-295 support multiple batteries with xcpmd

### PR DESCRIPTION
**Pull request by marslandd**
First release candidate for UI support of xcpmd

Requires the matching version of the xcpmd library as well as the SELinux security policy that supports xcpmd

### CODE REVIEW

**Comment by rossphilipson** [comment]
I will try this out.

**Comment by rossphilipson** [comment]
I just installed with this change and I get no batteries at all. Battery hot plugging does nothing. I would say this pull req. is busted.

**Comment by marslandd** [comment]
Hi Ross,

You need the latest xcpmd code from Jenn which includes the new batteries_available method, or else you will get this exact result due to the call being missing.

**Comment by rossphilipson** [comment]
There are not pull requests in xcpmd/xctools.git? You have lost me.

**Comment by jean-edouard** [comment]
@marslandd, if this pull request is incompatible with the current state of OpenXT, it should probably not have been created, or at the very least include a comment that tells us so.
It's the second time this week we tested a pull request from you that didn't make sense, wasting time and effort for nothing!

**Comment by marslandd** [comment]
Hi Jed,

As discussed on the call yesterday, I'm putting the pull request in pre-emptively as our contract is ending as of today and we won't be back for a couple of weeks at best. The code is tested against a build that includes Jenn's github repos as provided by her. It's my effort to keep from having the xcpmd feature set delayed due to not being on duty. 

I'm not aware of the state of Jenn's code base re: pull requests and she's been out the past couple of days. I'll discuss the state of the codebase for xcpmd with her this afternoon.

The second line of my comment on the pull request mentions that a new version of xcpmd needs to accompany it, perhaps I could have made that a bit clearer.

Sorry for any inconvenience this has caused. 

Dave

**Comment by jean-edouard** [comment]
Thanks for clarifying.
The call you're mentioning was internal, people in the community are not aware of what was discussed.

We try to handle pull requests as quickly as possible after they get created. As you are not "requesting" that we "pull" it just yet, this "pull request" should have had a big red flag mentioning the very special situation...

**Comment by jctemkin** [comment]
The pull requests that add the RPCs in question to XCPMD were merged as of September 3rd. It's possible that these calls may not be present if the packages xenclient-idl, xenclient-rpcgen, and xenclient-rpcgen-native were not cleaned and rebuilt between the IDL update and building XCPMD. You can test to see if this is the case by running the command "dbus-send --system --print-reply --dest=com.citrix.xenclient.xcpmd / com.citrix.xenclient.xcpmd.batteries_present". If it fails, try cleaning and rebuilding those three packages, then XCPMD, and see if the problem persists.

**Comment by rossphilipson** [comment]
Started a build (301) to test this.

**Comment by rossphilipson** [comment]
This seems to be working so +1 on that side of things. We tested on our laptop with a hot pluggable battery. It would be great if someone could look over the code though. I am not familiar with this javascript dojo stuffs at all.

**Comment by rossphilipson** [comment]
Will merge in a while soon...

**Pull request merged**
