### PR TITLE
3D Graphics PCI Pass Through Prompt

### PR DESCRIPTION
**Pull request by pentadoc**
Add a dialog that prompts the user so that they are aware of any
other PCI devices on the 3d card's bus that will be passed through
to the guest.

Expected behavior:

In the VM Details dialog, on hardware tab, the user makes a selection
in the "3D Graphics (experimental)" drop down.  A dialog should appear
if:
- There are other devices on the gpu bus that will be passed through
  AND
- The use makes a selection besides disabled (either Enabled or the
  specific card on multi-gpu boxes)

A dialog will appear warning a user about the other devices being
passed through, along with a list of those devices.

The user may click "OK" to dismiss the dialog, or "Cancel" which
sets the drop down to the last saved setting.  The top right "X" works
the same as "Cancel".

OXT-281

Signed-off-by: Andrew 'Doc' Docherty doc@coveycs.com

### CODE REVIEW

**Comment by crogers1** [comment]
Continuing the discussion from the previous PR:
https://github.com/OpenXT/manager/pull/12 handles the actual additional passthrough logic.  When the dialog is displayed to the user, no additional devices have actually been passed through yet.  It's purely meant to be an informational dialog.

@transpute:  The address of the device, seen from the UIVM, can be used to determined if the device relates to the GPU.  The address is parsed by the following format "Domain:Bus:Device:Function".  If the GPU is located at 0000:01:00.0, devices with 0000:01:00.x (where x is a number) are functions of the GPU.  In the previous example, the audio function is commonly seen as 0000:01:00.1.  In the unlikely case that there are multiple devices on the same bus as the GPU, you can use the bus value to determine which devices are on that bus.

There aren't any additional side effects to consider here since this ticket implements a purely informational change.

@pearsonk:
Once the GPU is assigned to the guest and the VM is started, the extra devices and functions will remain passed through to that guest until they are manually removed, persisting after VM reboot.  This particular point should be discussed on the xenmgr pull request if there is some issue with it.

**Comment by stacktrust** [comment]
When a GPU is passed through to a VM, does it appear in the list of "PCI passthrough" devices?

When a GPU-associated-device is passed through to a VM, does it appear in the list of "PCI passthrough" devices?

**Comment by crogers1** [comment]
@transpute:
Yes and yes.

**Comment by jean-edouard** [comment]
LGTM, will merge soon

**Pull request merged**
