### PR TITLE
OXT-295 - Support xcpmd instead of UPower interface

### PR DESCRIPTION
**Pull request by Marsland**
First interation of UI to support xcpmd - note: requires that the build
includes the xcpmd interface,  add xcpmd.xml to the IDLS variable in the
Makefile

### CODE REVIEW

**Comment by jean-edouard** [comment]
Could you please also submit a pull request for the Makefile changes you're describing?
That way I could automatically build the whole thing for testing.

**Comment by Marsland** [comment]
Here's your note from JIRA regarding that file. I'll go dig that up.

Jed added a comment - 12/Jun/15 11:59 AM
I'm not too familiar with the UI build system, but it looks like all you need to do is add xcpmd.xml to the IDLS variable in the Makefile (https://github.com/OpenXT/toolstack-data/blob/master/Makefile#L29).

**Comment by Marsland** [comment]
I just altered the current pull to include the changes as it's a part of toolstack-data

**Comment by jean-edouard** [comment]
Thank you, I'll build that.
Just a heads-up about the Makefile edit, the indentation is wrong, which could actually have an impact on the build, we never know with Makefiles :)

**Comment by Marsland** [comment]
Re: indentation: got it

**Comment by jean-edouard** [comment]
This builds but won't run because of the SELinux policy. It probably needs a couple new rules. Let me know if you need help for that.

**Comment by jean-edouard** [comment]
With SELinux off, it works but doesn't seem to refresh correctly.

**Comment by Marsland** [comment]
Yes, I saw an SELinux warning come up when I tried downloading the new code to the test laptop. First time I'd seen that. But refreshing the browser session made it disappear. Let me know where I need to start looking to resolve that. Other than that, can you give me more details on the 'not refresh correctly' observation? It looks OK to me.

**Comment by jean-edouard** [comment]
- The SELinux policy rules are in the form of patches against the reference policy. You can find the files there: `https://github.com/OpenXT/xenclient-oe/tree/master/recipes-security/selinux/refpolicy-mcs`
  The OpenEmbedded target is "refpolicy-mcs", you can find the code with patches (quilt-)applied in your build tree, under `tmp-eglibc/work/xenclient_dom0-oe-linux/refpolicy-mcs-*/refpolicy`
  Adding the proper rules is critical. Please create a ticket if you can't figure it out.
- After disabling SELinux and rebooting my HP EliteBook 850 G1, I get the battery icon with correct information. Then I unplug the AC and hover the icon to see the status of the battery, and is stays at "Fully Charged" forever, or until I restart the UI (ctrl+Q). After restarting, the icon and the hover text are correct.

**Comment by Marsland** [comment]
Got it. It sounds like the latter issue is either not getting the refreshed battery status at the time of the battery_status_changed or not receiving signals over DBus due to the messages being denied.

I'll take a look at the rules. Perhaps getting that operational will resolve the issue with incorrect status after unplugging AC. I haven't seen that behavior locally or else I wouldn't have submitted the code, so something is afoot there and I'll track it down once I've resolved the SELinux issue.

Thanks!

**Comment by jean-edouard** [comment]
Actually that second issue (no refresh) is expected, as the pull request to fix the signal timing is not in yet...

**Comment by Marsland** [comment]
I know why we didn't see this earlier. Since we develop the UI in a remote session, one of the first things we do to enable that process is to issue "setenforce 0" which is turning SELinux off, before going on to set up ssh and v4v-proxy. So we've been developing without that layer enabled.

**Comment by Marsland** [comment]
Roger that on the refresh issue.

**Comment by Marsland** [comment]
I've edited the patch for xenpmd to add permission to send to dbusbouncer and submitted a pull request for xenclient-oe.

**Comment by jean-edouard** [comment]
Nice! I'll test this later.
For easy reference: https://github.com/OpenXT/xenclient-oe/pull/147

**Comment by jean-edouard** [comment]
@Marsland this PR is still relevant, right?
I guess it depends on https://github.com/OpenXT/xctools/pull/13 to work properly, I'll re-test and merge this PR after https://github.com/OpenXT/xctools/pull/13.
Once this is merged, we should remove upower from OpenXT.

**Comment by Marsland** [comment]
Yes, that's correct! We also need that other piece from oeclient for the SELinux policy fix (sorry, I'm offsite, don't have the pull request in front of me) to allow DBus to send xcpmd messages to uivm as well. 

All references to UPower on the UI side were removed in the first xcpmd implementation submitted earlier. References to UPower in other area of the overall project will need to get excised, yes.

**Comment by jean-edouard** [comment]
I build and installed https://github.com/OpenXT/xctools/pull/13 on top of a fresh build.
Then I built and installed this PR.
I'm using a laptop with 3 battery slots, BAT0 wired to the internal battery, BAT1 wired to nothing and BAT2 wired to an "external" battery.
After booting, I get the following error message in the UIVM: "No such battery slot", and only one battery appears at the bottom. Looks like the UI is trying to get information for the absent BAT1.

**Comment by Marsland** [comment]
Yes.  We still are working on multi-battery support with Jenn's new xcpmd release which will provide us with an array of valid battery numbers. 

Also still waiting on a battery to set up one of our Dell laptops with two batteries so we can reproduce something closer to your setup. We have no units in Rome with 3 batteries at this time.

**Comment by jean-edouard** [comment]
So I think you should close this pull request and open a new one once things are figured out.
Merging this would cause a regression.

**Comment by Marsland** [comment]
OK. The new xcpmd development has obsoleted this version.

**Comment by jean-edouard** [comment]
Makes sense. Please close the pull request when you get the chance. I guess https://github.com/OpenXT/xenclient-oe/pull/147 can stay open and be merged anytime though.

**Comment by Marsland** [comment]
I'll close the pull request when I'm onsite tomorrow. And yes, 147 needs to be merged regardless.

**Pull request closed without merging**
