### PR TITLE
Standardize code to UNIX-style line endings

### PR DESCRIPTION
**Pull request by bennettj1087**
OXT-121

Signed-off-by: Justin Bennett bennettj@ainfosec.com

### CODE REVIEW

**Comment by thegecko** [comment]
I'm _really_ uncomfortable about mass changes like these as they can easily hide unwanted changes not apparent in diffs.

**Comment by bennettj1087** [comment]
Do you have an alternative suggestion? We've been applying a whitespace
patch internally in order to make modifying these files easier and haven't
run in to any issues.  This is that exact patch applied and committed.
It's becoming burdensome since now anytime there are modifications to any
of the DOS-style files, I have to manually regenerate our whitespace patch
in order for it to apply properly.

I'm all ears for other ideas, this just seemed the simplest to me.

**Comment by thegecko** [comment]
I think we used autocrlf:

http://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#Formatting-and-Whitespace

**Comment by cjp256** [comment]
What about posting the script line used to make the diff, and have someone else verify the patch?  I'm guessing it was just a simple one liner.  Should be easy enough to validate...

**Comment by jean-edouard** [comment]
Like @thegecko, I'm usually against that kind of massive change, because it completely breaks very useful tools like git blame.

However, right now this repo has just 2 (relevant) commits, so I'm not against this pull request...

I agree with @cjp256 that for that kind of commit it can be very useful to include the script that was used to generate the diff.

**Comment by rossphilipson** [comment]
I also agree with @thegecko in general. In this case I think we should do it since there is very little history and if we wait, it would just make it worse to do it. So +1 from me.

**Comment by flihp** [comment]
If there are side effects that cause breakage there hasn't been much churn so there won't be any confusion over where the issue came from. Sounds like a great opportunity to get something cleaned up that would otherwise be difficult.

**Comment by thegecko** [comment]
Would you mind holding off merging this PR until I can scan through the file changes?

**Comment by flihp** [comment]
AFAIK there's no rush. Reviews == good.

**Comment by thegecko** [comment]
OXT-121 Looks closed with little comment, I assume all are in favour of no longer supporting UI development on Windows? We decided to have Windows line endings as it was a reasonable compromise to allow development on Windows or Linux systems.

If we want to mandate Linux development environments, probably should drop support for the batch file build scripts.

P.S. still scanning the PR :)

**Comment by bennettj1087** [comment]
I don't think we should drop support for Windows, and I don't think anyone
else would say that either. Once this PR is merged, we can use a git
attributes file to force git autocrlf to the correct value so that those
using it on Windows will get Windows line-endings without even knowing it.
Also, anyone using a reasonable editor in Windows won't even notice if the
files are UNIX-style anyway, since most editors just handle it in the
background.

**Comment by bennettj1087** [comment]
Also, OXT-121 isn't closed as far as I can tell.

**Comment by thegecko** [comment]
OK, can you help me understand why the existing line endings being changed using autocrlf for use on unix-based systems is different from changing all line endings and using a similar technique on Windows?

**Comment by bennettj1087** [comment]
On Mon, Feb 2, 2015 at 9:08 AM, Rob Moran notifications@github.com wrote:

> OK, can you help me understand why the existing line endings being changed
> using autocrlf for use on unix-based systems is different from changing all
> line endings and using a similar technique on Windows?
> 
> I may not have a complete understanding of how autocrlf works, but the way
> it looks is that if you set autocrlf to input then git will automatically
> convert everything to LF on commit.  Which as the repo stands right now
> would mean that anytime someone touches a file with CRLF line endings, it
> would get auto converted to LF and there would be a big diff.

My thought behind doing one large line ending commit now is to standardize the 
repo to one style, rather than having a mix. Then, we set autocrlf to input
and git manages it without anyone having to care anymore. We have one
large, simple diff to look at now and in the future we shouldn't have to
worry about it anymore.

That said, I'm almost ready to stop caring. I didn't think it was going to
turn into a big debate on how to manage line endings. If you have a better
way to do it, please feel free to just do that instead.

**Comment by thegecko** [comment]
It was my impression all files currently have Windows line endings.
If this isn't the case and there is a mixture, I'm all for standardising, we just need a reason to go one way or the other. This could be as simple as "the majority of development is done on unix-like systems".

**Comment by bennettj1087** [comment]
Ah, I believe there is a fair mixture. When we started working on this
internally the first patch in our queue to was to patch to UNIX-style line
endings so that there was not a mixture.  I can't say I care one way or the
other whether it is LF or CRLF. Everyone that I have worked with on the
project so far is using Linux for development so that made the most sense
to me.

From what I can tell, Windows users can set autocrlf to true and they will
never know that the files actually have LF endings.  Going the other
direction (have git keep files as CRLF) seems like it is not intended which
is another reason to house files as LF and use git to present CRLF to users
who like them better.

**Comment by rossphilipson** [comment]
Have people reached consensus on this?

**Comment by thegecko** [comment]
I believe we have agreed on unix endings, but I haven't yet had time to scan the PR for anything else 'creeping in' :)

**Comment by bennettj1087** [comment]
Closing this and opening a new one based on some diffs I'm doing.  The new one will have a description of the commands I used to generate the patch.

**Pull request closed without merging**
