### PR TITLE
3D Graphics PCI Pass Through Prompt

### PR DESCRIPTION
**Pull request by pentadoc**
Add a dialog that prompts the user so that they are aware of any
other PCI devices on the 3d card's bus that will be passed through
to the guest.

Expected behavior:

In the VM Details dialog, on hardware tab, the user makes a selection
in the "3D Graphics (experimental)" drop down.  A dialog should appear
if:
- There are other devices on the gpu bus that will be passed through
  AND
- The use makes a selection besides disabled (either Enabled or the
  specific card on multi-gpu boxes)

A dialog will appear warning a user about the other devices being
passed through, along with a list of those devices.

The user may click "OK" to dismiss the dialog, or "Cancel" which
sets the drop down to the last saved setting.  The top right "X" works
the same as "Cancel".

OXT-281

Signed-off-by: Andrew 'Doc' Docherty doc@coveycs.com

### CODE REVIEW

**Comment by jean-edouard** [comment]
Your branch (pentadoc:OXT-281_3D_Graphics_Change_Prompt) seems to be based on iansmills:master, instead of the latest OpenXT:master.
It would be useful if you could rebase it so that I can start a build that includes this pull request to test it.

**Comment by stacktrust** [comment]
After a multi-device GPU has been passed through to a guest, will the VM details panel in the UIVM (and/or the API) report the name and address of all PCI devices associated with the GPU?

**Comment by pentadoc** [comment]
@transpute this screenshot shows what is reported to the user.  In this case only one other device was on the same bus, but if there were more then the entire list would be shown. 

screenshot from 2015-05-20 11 44 33

**Comment by pentadoc** [comment]
@jean-edouard closing this request, rebased my repo on OpenXT:master and resubmitted request,

https://github.com/OpenXT/toolstack-data/pull/20

**Comment by stacktrust** [comment]
@pentadoc Thanks for the screenshot of the pre-passthrough UX.  On a machine where a GPU and associated devices have already been passed through to a VM, is there any way to determine the list of GPU-related devices from the UIVM?

**Comment by pentadoc** [comment]
@transpute I don't believe there is. Should it be a new ticket to display passed-through devices on the PCI Pass Through tab of the VM Details dialog?

**Comment by stacktrust** [comment]
The current ticket could be amended to cover all changes related to communicating "GPU passthrough side-effects" to the user, whether before or after the PT action.  Or create an epic top-level ticket that aggregates API and UI tickets for GPU PT and related side-effects.

**Comment by pearsonk** [comment]
Apologies for the necrobump, but if the background logic is manually doing the association, it is quite likely that all the devices would show up on the "PCI Pass Through" tab of the VM details. If this is true, I would hope that there is logic in place to prevent removal of these devices causing the split that the work in this ticket and the toolstack changes are designed to prevent.

**Pull request closed without merging**
